# Generated by Django 3.1.5 on 2021-01-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_value', models.IntegerField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'budget',
                'managed': False,
            },
        ),
    ]
