# Generated by Django 3.1.5 on 2021-01-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
